// Package correct automatically cleans up prose text parsed from the
// sourcebook PDFs before it ever reaches the rules database — spelling
// (misspell); a narrow grammar heuristic for false plural-possessives
// ("Katana's" -> "Katanas"); a stray-hyphen-space compound-word splitter
// ("D- Rank" -> "D-Rank"); a dropped-possessive-apostrophe fixer
// ("a creatures cells" -> "a creature's cells"); a closed set of real-word
// confusions ("allay" -> "ally"); a curated list of one-off, context-
// dependent fixes that can't be expressed as a safe general rule; and real
// grammar via the public LanguageTool API. This runs silently: the user
// chose full auto-correction over a
// manual review step, which is a deliberate departure from this codebase's
// usual "always flag for a human" convention (see internal/validate). The
// only trace left behind is an append-only audit table
// (internal/store.WriteTextCorrections) that nothing surfaces automatically.
//
// Correction happens on the parsed struct in place, before it's handed to
// internal/store. Prose columns have no *_override mechanism (checked: none
// exist in the schema) — they're already fully regenerated by every
// ingestion run, so correcting the text here doesn't fight the override
// system, it's the same "always regenerate the parsed value" pattern the
// rest of the pipeline already uses, just with a correction step folded
// into what gets regenerated.
package correct

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"net/http"
	"reflect"
	"sort"
	"strings"
)

// Record is one applied correction, ready to be logged to the
// text_corrections audit table by internal/store.WriteTextCorrections.
type Record struct {
	EntityType, EntityPath, Field string
	Tool                          string // "misspell", "apostrophe", "hyphenspace", "possessive", "wordconfusion", "curated", or "languagetool"
	RuleID                        string // LanguageTool rule id; "" for every other tool
	Original, Corrected           string
}

// Report summarizes one Sweep call.
type Report struct {
	FieldsScanned       int
	MisspellFixes       int
	ApostropheFixes     int
	HyphenSpaceFixes    int
	PossessiveFixes     int
	WordConfusionFixes  int
	LanguageToolFixes   int
	LanguageToolSkipped int
	CuratedFixes        int
	Warnings            []string
	Records             []Record
}

// Options configures a Sweep.
type Options struct {
	SkipLanguageTool bool // true for dry runs: keep parser iteration fast, offline, and off the shared public quota
	Cache            *Cache
	HTTPClient       *http.Client // nil -> a sane default; injectable for tests
	BaseURL          string       // override for tests; defaults to the public API
}

type textDiff struct {
	tool, ruleID, original, corrected string
}

// unit is one prose field discovered by the reflection walk: an
// addressable string field ready to be corrected in place.
type unit struct {
	entityType, entityPath, field string
	value                         reflect.Value
	text                          string
}

// Sweep walks v (a pointer to a slice of parsed entities, e.g. &clans),
// corrects every registered prose field (see registry.go) in place, and
// returns a report of what changed. It returns a non-nil error only for a
// programmer mistake (v isn't a pointer to a slice) — never for network or
// rate-limit problems, which become Warnings so a maintainer's ingest run
// never hard-fails because a third-party grammar API is unreachable.
func Sweep(ctx context.Context, v any, opts Options) (*Report, error) {
	rv := reflect.ValueOf(v)
	if rv.Kind() != reflect.Pointer || rv.Elem().Kind() != reflect.Slice {
		return nil, fmt.Errorf("correct.Sweep: v must be a pointer to a slice, got %T", v)
	}

	rep := &Report{}
	var units []*unit
	collect(rv.Elem(), "", &units, rep)

	// Pass 1: misspell — local, instant, always runs.
	for _, u := range units {
		fixed, diffs := misspellFix(u.text)
		for _, d := range diffs {
			rep.Records = append(rep.Records, Record{u.entityType, u.entityPath, u.field, d.tool, d.ruleID, d.original, d.corrected})
		}
		rep.MisspellFixes += len(diffs)
		u.text = fixed
	}

	// Pass 2: the list-context apostrophe heuristic — local, instant,
	// always runs, operates on the misspell-corrected text.
	for _, u := range units {
		fixed, diffs := apostropheFix(u.text)
		for _, d := range diffs {
			rep.Records = append(rep.Records, Record{u.entityType, u.entityPath, u.field, d.tool, d.ruleID, d.original, d.corrected})
		}
		rep.ApostropheFixes += len(diffs)
		u.text = fixed
	}

	// Pass 3: LanguageTool — network, rate-limited, skippable.
	if !opts.SkipLanguageTool {
		sweepLanguageTool(ctx, units, opts, rep)
	}

	// Pass 4: hyphen-space — local, instant, always runs. Operates after
	// LanguageTool so its allowlist sees whatever LT left behind, same as
	// apostrophe operating after misspell.
	for _, u := range units {
		fixed, diffs := hyphenSpaceFix(u.text)
		for _, d := range diffs {
			rep.Records = append(rep.Records, Record{u.entityType, u.entityPath, u.field, d.tool, d.ruleID, d.original, d.corrected})
		}
		rep.HyphenSpaceFixes += len(diffs)
		u.text = fixed
	}

	// Pass 5: dropped possessive apostrophe — local, instant, always runs.
	for _, u := range units {
		fixed, diffs := possessiveFix(u.text)
		for _, d := range diffs {
			rep.Records = append(rep.Records, Record{u.entityType, u.entityPath, u.field, d.tool, d.ruleID, d.original, d.corrected})
		}
		rep.PossessiveFixes += len(diffs)
		u.text = fixed
	}

	// Pass 6: closed-set real-word confusions (e.g. "allay" -> "ally") —
	// local, instant, always runs.
	for _, u := range units {
		fixed, diffs := wordConfusionFix(u.text)
		for _, d := range diffs {
			rep.Records = append(rep.Records, Record{u.entityType, u.entityPath, u.field, d.tool, d.ruleID, d.original, d.corrected})
		}
		rep.WordConfusionFixes += len(diffs)
		u.text = fixed
	}

	// Pass 7: curated one-off corrections — local, instant, always runs.
	// Runs last so each entry's Original key can be written against the
	// text as every other pass has already left it.
	for _, u := range units {
		fixed, diffs := curatedFix(u.text)
		for _, d := range diffs {
			rep.Records = append(rep.Records, Record{u.entityType, u.entityPath, u.field, d.tool, d.ruleID, d.original, d.corrected})
		}
		rep.CuratedFixes += len(diffs)
		u.text = fixed
	}

	for _, u := range units {
		u.value.SetString(u.text)
	}
	return rep, nil
}

func sweepLanguageTool(ctx context.Context, units []*unit, opts Options, rep *Report) {
	var pending []*unit
	for _, u := range units {
		if len([]rune(u.text)) > maxBatchChars {
			// Pathological case (a single field longer than LanguageTool's
			// own per-request cap) — skip LT for this one field rather than
			// fail the whole batch; it still has whatever misspell/
			// apostrophe already fixed.
			continue
		}
		if opts.Cache != nil {
			if cached, ok := opts.Cache.Get(u.text); ok {
				applyCached(u, cached, rep)
				continue
			}
		}
		pending = append(pending, u)
	}
	if len(pending) == 0 {
		return
	}

	lt := newLanguageTool(opts.HTTPClient, opts.BaseURL)
	batches := buildBatches(pending, maxBatchChars)
	for i, b := range batches {
		matches, err := lt.check(ctx, b.text)
		if err != nil {
			skipped := 0
			for _, rem := range batches[i:] {
				skipped += len(rem.spans)
			}
			rep.Warnings = append(rep.Warnings, fmt.Sprintf(
				"languagetool: %v — grammar pass skipped for %d remaining field(s)", err, skipped))
			return
		}
		applyBatchMatches(b, matches, opts.Cache, rep)
	}
}

func applyCached(u *unit, cached cachedResult, rep *Report) {
	u.text = cached.CorrectedText
	for _, cr := range cached.Records {
		rep.Records = append(rep.Records, Record{u.entityType, u.entityPath, u.field, cr.Tool, cr.RuleID, cr.Original, cr.Corrected})
		if cr.Tool == "languagetool" {
			rep.LanguageToolFixes++
		}
	}
}

type batchSpan struct {
	u          *unit
	start, end int // rune offsets into batch.text
}

type batch struct {
	text  string
	spans []batchSpan
}

// buildBatches greedily packs units into requests near maxChars, joining
// with "\n\n" — verified live against the real LanguageTool API that this
// separator stops matches from straddling two fields' text, which is what
// makes mapping each match back to its originating unit unambiguous.
func buildBatches(units []*unit, maxChars int) []batch {
	var batches []batch
	var cur batch
	curLen := 0
	for _, u := range units {
		textLen := len([]rune(u.text))
		sepLen := 0
		if curLen > 0 {
			sepLen = 2
		}
		if curLen > 0 && curLen+sepLen+textLen > maxChars {
			batches = append(batches, cur)
			cur = batch{}
			curLen = 0
		}
		if curLen > 0 {
			cur.text += "\n\n"
			curLen += 2
		}
		start := curLen
		cur.text += u.text
		curLen += textLen
		cur.spans = append(cur.spans, batchSpan{u: u, start: start, end: curLen})
	}
	if curLen > 0 {
		batches = append(batches, cur)
	}
	return batches
}

func applyBatchMatches(b batch, matches []ltMatch, cache *Cache, rep *Report) {
	perUnit := map[*unit][]ltMatch{}
	for _, m := range matches {
		span := findSpan(b.spans, m.Offset, m.Length)
		if span == nil || !acceptMatch(m) {
			rep.LanguageToolSkipped++
			continue
		}
		perUnit[span.u] = append(perUnit[span.u], m)
	}

	// Every unit in this batch gets a cache entry, even with zero
	// LanguageTool matches — that's what makes an unchanged field cost
	// zero requests on the next ingest.
	for _, span := range b.spans {
		u := span.u
		ms := perUnit[u]
		sort.Slice(ms, func(i, j int) bool { return ms[i].Offset > ms[j].Offset }) // right-to-left, so earlier offsets stay valid as later ones are applied

		before := u.text
		runes := []rune(u.text)
		var recs []Record
		for _, m := range ms {
			local := m.Offset - span.start
			if local < 0 || local+m.Length > len(runes) {
				rep.LanguageToolSkipped++
				continue
			}
			repl := m.Replacements[0].Value
			original := string(runes[local : local+m.Length])
			runes = append(runes[:local:local], append([]rune(repl), runes[local+m.Length:]...)...)
			recs = append(recs, Record{u.entityType, u.entityPath, u.field, "languagetool", m.Rule.ID, original, repl})
		}
		u.text = string(runes)
		rep.LanguageToolFixes += len(recs)
		rep.Records = append(rep.Records, recs...)

		if cache != nil {
			cached := make([]cachedRecord, len(recs))
			for i, r := range recs {
				cached[i] = cachedRecord{Tool: r.Tool, RuleID: r.RuleID, Original: r.Original, Corrected: r.Corrected}
			}
			cache.Put(before, cachedResult{CorrectedText: u.text, Records: cached})
		}
	}
}

func findSpan(spans []batchSpan, offset, length int) *batchSpan {
	for i := range spans {
		if offset >= spans[i].start && offset+length <= spans[i].end {
			return &spans[i]
		}
	}
	return nil
}

// collect recurses through v (a struct, slice, or pointer) discovering
// every prose field registered in proseFields, regardless of how deeply
// it's nested (Clan.Features[].Description, Clan.Jutsu[].Description, ...).
// A struct's Name field, when present, extends the audit path so
// EntityPath reads like "hebi-clan/weapon-proficiencies" rather than a bare
// field name.
func collect(v reflect.Value, pathPrefix string, units *[]*unit, rep *Report) {
	switch v.Kind() {
	case reflect.Pointer:
		if !v.IsNil() {
			collect(v.Elem(), pathPrefix, units, rep)
		}
	case reflect.Slice, reflect.Array:
		for i := 0; i < v.Len(); i++ {
			collect(v.Index(i), pathPrefix, units, rep)
		}
	case reflect.Struct:
		t := v.Type()
		path := pathPrefix
		if nf := v.FieldByName("Name"); nf.IsValid() && nf.Kind() == reflect.String && nf.String() != "" {
			path = joinPath(pathPrefix, auditSlug(nf.String()))
		}
		for _, fname := range proseFields[t] {
			fv := v.FieldByName(fname)
			if fv.IsValid() && fv.Kind() == reflect.String && fv.String() != "" {
				*units = append(*units, &unit{entityType: t.Name(), entityPath: path, field: fname, value: fv, text: fv.String()})
				rep.FieldsScanned++
			}
		}
		for i := 0; i < t.NumField(); i++ {
			sf := t.Field(i)
			if sf.PkgPath != "" { // unexported
				continue
			}
			switch sf.Type.Kind() {
			case reflect.Struct, reflect.Slice, reflect.Array, reflect.Pointer:
				collect(v.Field(i), path, units, rep)
			}
		}
	}
}

func joinPath(prefix, seg string) string {
	if prefix == "" {
		return seg
	}
	if seg == "" {
		return prefix
	}
	return prefix + "/" + seg
}

// auditSlug is a small, local, audit-label-only slugifier — deliberately
// not store.Slugify: internal/store needs to import internal/correct (for
// Record, in WriteTextCorrections), so correct must not import store.
func auditSlug(name string) string {
	var b strings.Builder
	pendingHyphen := false
	for _, r := range strings.ToLower(name) {
		switch {
		case r >= 'a' && r <= 'z' || r >= '0' && r <= '9':
			if pendingHyphen && b.Len() > 0 {
				b.WriteByte('-')
			}
			pendingHyphen = false
			b.WriteRune(r)
		case r == '\'' || r == '’':
			// drop, no hyphen
		default:
			pendingHyphen = true
		}
	}
	return b.String()
}

func contentHash(s string) string {
	sum := sha256.Sum256([]byte(s))
	return hex.EncodeToString(sum[:])
}
